name: Deploy Validator Dashboard Site to GitHub Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["master"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Debug Information
        run: |
          echo "GitHub Actions Environment Debug"
          echo "Runner OS: ${{ runner.os }}"
          echo "Runner Temp: $RUNNER_TEMP"
          echo "GitHub Workspace: $GITHUB_WORKSPACE"
          pwd
          ls -la
      
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'
      
      - name: Setup Pages
        uses: actions/configure-pages@v4
      
      - name: Restore NPM Cache
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            .next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-
      
      - name: Install Dependencies
        run: |
          npm ci
          echo "Installed dependencies successfully"

      - name: Run Linter
        run: npm run lint

      - name: Build Next.js Application
        run: |
          npm run build
          echo "Build completed successfully"
          ls -la out/
      
      - name: Static Export
        run: npm run export  # Ensure this script exists in package.json
      
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: static-site
          path: out/
          retention-days: 1

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: static-site
          path: out/
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3
        
      - name: Deployment Verification
        run: |
          echo "Deployment URL: ${{ steps.deployment.outputs.page_url }}"
          curl -f ${{ steps.deployment.outputs.page_url }}

  # Optional: Post-deployment checks
  post-deploy:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Verify Deployment
        run: |
          echo "Deployment completed successfully" 